import "@radix-ui/themes/styles.css";
import { Box, Theme } from "@radix-ui/themes";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          background:
            "linear-gradient(90deg, rgba(255,89,0,1) 0%, rgba(255,141,0,1) 100%)",
        }}
        className={inter.className}
        suppressHydrationWarning>
        <Theme>
          {/* <Box position={"absolute"} top={"0"} style={{ zIndex: 10 }}>
            <Navbar />
          </Box> */}
          {children}
        </Theme>
      </body>
    </html>
  );
}
