import "@radix-ui/themes/styles.css";
import { Box, Theme } from "@radix-ui/themes";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Provider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "All In One Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        <Provider>
          <Theme>
            {/* <Box position={"absolute"} top={"0"} style={{ zIndex: 10 }}>
            <Navbar />
          </Box> */}
            {children}
          </Theme>
        </Provider>
      </body>
    </html>
  );
}
